version: 3.1.unstable.{build}
skip_tags: true
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  project: AFT_Online_Tool_Box.sln
  verbosity: minimal
artifacts:
- path: PDAFT_Online_ToolBox.exe
