version: 3.4.unstable.{build}
skip_tags: true
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  project: AFT_Online_Tool_Box.sln
  verbosity: minimal
after_build:
- cmd: "mkdir PDAFT-Online-Toolbox\ncopy bin\\Release\\PDAFT_Online_Toolbox.exe PDAFT-Online-Toolbox\nxcopy SegaTools PDAFT-Online-Toolbox /E /Y  \nxcopy PD-Loader PDAFT-Online-Toolbox /E /Y"
artifacts:
- path: PDAFT-Online-Toolbox
  name: PDAFT-Online-Toolbox